title: Kyle Holcomb - Security Professional & Claude Code Enthusiast
description: Personal website of Kyle Holcomb - Security Professional, Cloud Architect, and Open Source Contributor
url: https://kholcomb.github.io
baseurl: ""

# Jekyll configuration
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-redirect-from

# Blog configuration
paginate: 5
paginate_path: "/blog/page:num/"
excerpt_separator: "<!--more-->"

# Permalink structure for blog posts
permalink: /blog/:year/:month/:day/:title/

# Theme configuration for different versions
collections:
  themes:
    output: true
    permalink: /:name/

# Default theme (none - use custom CSS)
theme: null

# Build settings
safe: true
incremental: false

# Blog settings
blog:
  title: "Security Insights"
  description: "Thoughts on cloud security, Kubernetes, and building secure systems"
  author: "Kyle Holcomb"